//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16 [unused]
//   float3 gFresnelR0;                 // Offset:   16 Size:    12 [unused]
//   float gRoughness;                  // Offset:   28 Size:     4 [unused]
//   float4x4 gMatTransform;            // Offset:   32 Size:    64
//   int gUseTexture;                   // Offset:   96 Size:     4 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  448
//       float FalloffStart;            // Offset:  460
//       float3 Direction;              // Offset:  464
//       float FalloffEnd;              // Offset:  476
//       float3 Position;               // Offset:  480
//       float SpotPower;               // Offset:  492
//
//   } gLights[16];                     // Offset:  448 Size:   768 [unused]
//   float4 gFogColor;                  // Offset: 1216 Size:    16 [unused]
//   float gFogStart;                   // Offset: 1232 Size:     4 [unused]
//   float gFogRange;                   // Offset: 1236 Size:     4 [unused]
//   float2 reserve;                    // Offset: 1240 Size:     8 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbMaterial                        cbuffer      NA          NA            cb1      1 
// cbPass                            cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[8], immediateIndexed
dcl_constantbuffer CB1[4], immediateIndexed
dcl_constantbuffer CB2[20], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyz
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xy
dcl_temps 5
//
// Initial variable locations:
//   v0.x <- vin.PosL.x; v0.y <- vin.PosL.y; v0.z <- vin.PosL.z; 
//   v1.x <- vin.NormalL.x; v1.y <- vin.NormalL.y; v1.z <- vin.NormalL.z; 
//   v2.x <- vin.TexC.x; v2.y <- vin.TexC.y; 
//   o3.x <- <VS return value>.TexC.x; o3.y <- <VS return value>.TexC.y; 
//   o2.x <- <VS return value>.NormalW.x; o2.y <- <VS return value>.NormalW.y; o2.z <- <VS return value>.NormalW.z; 
//   o1.x <- <VS return value>.PosW.x; o1.y <- <VS return value>.PosW.y; o1.z <- <VS return value>.PosW.z; 
//   o0.x <- <VS return value>.PosH.x; o0.y <- <VS return value>.PosH.y; o0.z <- <VS return value>.PosH.z; o0.w <- <VS return value>.PosH.w
//
#line 98 "C:\MyWork\FireFlame\Samples\Blend_Sample\Shaders\BlendApp.hlsl"
mov r0.xyz, v0.xyzx
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, cb0[0].xyzw  // r1.x <- posW.x
dp4 r1.y, r0.xyzw, cb0[1].xyzw  // r1.y <- posW.y
dp4 r1.z, r0.xyzw, cb0[2].xyzw  // r1.z <- posW.z
dp4 r1.w, r0.xyzw, cb0[3].xyzw  // r1.w <- posW.w

#line 99
mov r1.xyz, r1.xyzx  // r1.x <- vout.PosW.x; r1.y <- vout.PosW.y; r1.z <- vout.PosW.z

#line 102
dp3 r0.x, v1.xyzx, cb0[0].xyzx  // r0.x <- vout.NormalW.x
dp3 r0.y, v1.xyzx, cb0[1].xyzx  // r0.y <- vout.NormalW.y
dp3 r0.z, v1.xyzx, cb0[2].xyzx  // r0.z <- vout.NormalW.z

#line 105
dp4 r2.x, r1.xyzw, cb2[16].xyzw  // r2.x <- vout.PosH.x
dp4 r2.y, r1.xyzw, cb2[17].xyzw  // r2.y <- vout.PosH.y
dp4 r2.z, r1.xyzw, cb2[18].xyzw  // r2.z <- vout.PosH.z
dp4 r2.w, r1.xyzw, cb2[19].xyzw  // r2.w <- vout.PosH.w

#line 108
mov r3.xy, v2.xyxx
mov r3.zw, l(0,0,0,1.000000)
dp4 r4.x, r3.xyzw, cb0[4].xyzw  // r4.x <- texC.x
dp4 r4.y, r3.xyzw, cb0[5].xyzw  // r4.y <- texC.y
dp4 r4.z, r3.xyzw, cb0[6].xyzw  // r4.z <- texC.z
dp4 r4.w, r3.xyzw, cb0[7].xyzw  // r4.w <- texC.w

#line 109
dp4 r3.x, r4.xyzw, cb1[2].xyzw  // r3.x <- vout.TexC.x
dp4 r3.y, r4.xyzw, cb1[3].xyzw  // r3.y <- vout.TexC.y

#line 111
mov o0.xyzw, r2.xyzw
mov o1.xyz, r1.xyzx
mov o2.xyz, r0.xyzx
mov o3.xy, r3.xyxx
ret 
// Approximately 27 instruction slots used
